src/profileData/vishwasnavadak.json

Fix: Add vishwasnavadak Portfolio.

---

src/profileData/mrepol742.json

Fix: Add mrepol742 Portfolio.

---

src/profileData/Nix-Code.json

Fix: Add Nix-Code's Portfolio

---

src/profileData/Nailheart.json

Fix: Add Nailheart's Portfolio.

---

src/profileData/4Furki4.json

Fix: Add 4Furki4's Portfolio.

---

src/profileData/sirLisko.json

add sirLisko's portfolio

---

src/profileData/dimitrisraptis96.json

Fix: Add dimitrisraptis96's Portfolio.

---

src/profileData/yashitanamdeo.json

Fix: Add yashitanamdeo's Portfolio

---

src/profileData/iamswapnil22.json

Fix:Add iamswapnil22's Portfolio

---

src/profileData/elmonickcool.json

Add elmonickcool's Portfolio

---

src/profileData/vidjul.json

Fix: Add vidjul's Portfolio.

---

src/profileData/dinogomez.json

Closes [#62](https://github.com/Kiran1689/Awesome-Dev-Portfolios/issues/62)

Fix: Add Dinogomez's Portfolio.

---

src/profileData/LakshanRukantha.json

Add LakshanRukantha's Portfolio

---

README.md

I have replaced the existing website preview image in the README file with an updated mockup to enhance the user experience. This revision features a refined and more indicative website preview, providing users with a clearer insight into the visual preview of the project. This closes #72 
- Updated the website preview image in the README file.

Update the README live deployment preview with new mockup.

---

src/profileData/khaled-0.json

Fix: Add khaled-0's portfolio

---

src/profileData/gbgabiola.json

Fix: Add gbgabiola's Portfolio.

---

src/profileData/Ajay-Kannan7.json

Fix: Add Ajay-Kannan7's Portfolio

---

src/profileData/paalss.json

Fix: Add Paalss's Portfolio.

---

src/profileData/adityamedhe.json

Add adityamedhe's portfolio

---

src/profileData/MaheshBabu11.json

Fix: Add MaheshBabu11's Portfolio

---

src/profileData/himanshuchandola.json

Add himanshuchandola's Portfolio

---

src/Home.js

Add responsive navigation menu

---

src/profileData/Matt-code-d.json

Fix: Add Matt-code-d's Portfolio.

---

src/profileData/dobbe2.json

Fix: Add dobbe2's Portfolio.

---

src/profileData/rafnixg.json

Fix: Add rafnixg Portfolio

---

src/profileData/FrancesCoronel.json

Adding my portfolio after getting an email about this project! ✨

Add FrancesCoronel's Portfolio

---

src/profileData/Yaya12085.json

Fix: Add Yaya12085's Portfolio.

---

src/profileData/vinodjangid07.json

Fix: Add vinodjangid07's Portfolio

---

src/profileData/AladdineDev.json

Fix: Add AladdineDev's Portfolio.

---

src/profileData/RupendraSinghRajawat.json

Fix: Add RupendraSinghRajawat's Portfolio

---

src/profileData/SRX9.json

Fix: Add SRX9's Portfolio.

---

src/Home.js
src/components/user-auth-form-login.js
src/components/user-auth-form-signup.js

Hi team,
I've made a small adjustment to the home page component to improve responsiveness. Previously, I added `overflow-x-hidden` to "card 2" div to prevent horizontal scroll in mobile screen
Please review and let me know if there are any concerns or if you have alternative suggestions.
Thanks,
Anas mansy

Home responsive

---

src/profileData/anandbaraik.json

Fix: Add anandbaraik's Portfolio.

---

README.md

fixes #181 
- Changed the live deployment image in Readme.md file.

feat: change Live Deployment image in README.md

---

src/profileData/nirban256.json

Fix: Add nirban256's Portfolio

---

src/profileData/pcabreram1234.json

Fix: Add pcabreram1234's Portfolio.

---

src/profileData/akshay-rajan.json

Fix: Add akshay-rajan's portfolio

---

src/profileData/williamssam.json

Add williamssam portfolio

---

src/profileData/jameel-webdev.json

Fix: Add jameel-webdev's Portfolio.

---

src/profileData/andrewbaisden.json

Fix: Add andrewbaisden's Portfolio.

---

src/profileData/GregSithole.json

Fix: Add GregSithole's Portfolio.

---

src/profileData/luisjimenez19.json

Fix: Add luisjimenez19's Portfolio.

---

package-lock.json
src/components/ScrollToTopButton.css
src/components/ScrollToTopButton.js

Closes: #221 
Additional information: I had the button appear and disappear in a fade sort of a manner, to keep it consistent with the rest of the UI (like the portfolios fade in to view.)

Solves issue #221 

---

src/profileData/mittal-parth.json

Fix: Add mittal-parth's Portfolio

---

src/profileData/Vaibhav-kesarwani.json

Fix: Add Vaibhav-kesarwani Portfolio.

---

src/profileData/irungudennisnganga.json

update image size to 1900 x 900

Add irungudennisnganga

---

src/profileData/alejandrosobko.json

Fix: Add alejandrosobko's Portfolio

---

src/profileData/Maiz27.json

Fix: Add Maiz27's Portfolio

---

src/profileData/jaycode8.json

Add jaycode8's Portfolio

---

src/profileData/rafalmeida73.json

Closes https://github.com/Kiran1689/Awesome-Dev-Portfolios/issues/215

Add rafalmeida73 portfolio

---

src/profileData/oslo418.json

Closes https://github.com/Kiran1689/Awesome-Dev-Portfolios/issues/250

Add Oslo418's Portfolio

---

src/profileData/ChanMeng666.json

Fix: Add ChanMeng666's Portfolio

---

src/profileData/tvdsluijs.json

Fix: Add tvdsluijs's Portfolio.

---

src/profileData/RiteshS1.json

Add RiteshS1's Portfolio

---

src/profileData/mohankumarpaluru.json

Fix: Add mohankumarpaluru's Portfolio.

---

CONTRIBUTING.md
src/profileData/vishnu1100.json

So glad to be a part of this project

Add vishnu1100's Portfolio.

---

src/profileData/adex-hub.json

Fix: Add adex-hub's Portfolio.

---

src/profileData/Rodrigo-Suarez.json

Fix: Add Rodrigo-Suarez's Portfolio.

---

src/profileData/Divyanshu-Mishra9620.json

Add Divyanshu-Mishra9620's Portfolio

---

src/profileData/walkerrandolphsmith.json

Add walkerrandolphsmith's Portfolio
